package htmlselector

// TagName ...
type TagName string

// AttributeName ...
type AttributeName string

// OptimizedFilterGroup ...
type OptimizedFilterGroup map[TagName]AttributeFilterGroup

// AttributeFilterGroup ...
type AttributeFilterGroup map[AttributeName]struct{}
