required = [
  "github.com/alecthomas/gometalinter",
  "github.com/cweill/gotests/gotests",
]

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.6.1"

[[constraint]]
  name = "code.cloudfoundry.org/bytefmt"
  revision = "cf55d5288a48262e16d2e628b6221dd2df67bcd1"
