// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package htmlselector

import mock "github.com/stretchr/testify/mock"

// MockSelectionTerminator is an autogenerated mock type for the SelectionTerminator type
type MockSelectionTerminator struct {
	mock.Mock
}

// IsSelectionTerminated provides a mock function with given fields:
func (_m *MockSelectionTerminator) IsSelectionTerminated() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
