// Code generated by mockery v1.0.0. DO NOT EDIT.

package htmlselector

import mock "github.com/stretchr/testify/mock"

// MockBuilder is an autogenerated mock type for the Builder type
type MockBuilder struct {
	mock.Mock
}

// AddAttribute provides a mock function with given fields: name, value
func (_m *MockBuilder) AddAttribute(name []byte, value []byte) {
	_m.Called(name, value)
}

// FinishTag provides a mock function with given fields:
func (_m *MockBuilder) FinishTag() {
	_m.Called()
}

// StartTag provides a mock function with given fields: name
func (_m *MockBuilder) StartTag(name []byte) {
	_m.Called(name)
}
