// Code generated by mockery v1.0.0. DO NOT EDIT.

package htmlselector

import mock "github.com/stretchr/testify/mock"

// MockTextBuilder is an autogenerated mock type for the TextBuilder type
type MockTextBuilder struct {
	mock.Mock
}

// AddText provides a mock function with given fields: text
func (_m *MockTextBuilder) AddText(text []byte) {
	_m.Called(text)
}
